name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.config }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        arch: [x86, x86_64]
        python-version: ["3.8"]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Environment
      run: |
        # Update pip
        python -m pip install -U pip setuptools wheel

        # Install dependencies
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Build
      run: |
        mkdir ./build
        mkdir ./.temp
        pyinstaller Game/run.py --onefile --noconsole --clean --workpath ./.temp --distpath ./build --name WeirdLand
        cp -r ./Assets ./build
        cp ./icon.png ./build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: build/
        if-no-files-found: error
